# # ======================================================================================================================
# ### Talking Points: Dynamic text strings for translation
# ### Uses same pattern as DQ PowerPoint txt_ variables
# # ======================================================================================================================

txt_hpv_both_constant <- "Programme coverage of HPV1 among females remained constant at {hpv1_rev_cvg}% between {comp_yr} and {rev_yr}, and coverage of the last dose (HPVc) also remained constant at {hpvc_rev_cvg}%."
txt_hpv_hpv1_const_hpvc_inc <- "Programme coverage of HPV1 among females remained constant at {hpv1_rev_cvg}% between {comp_yr} and {rev_yr}, while coverage of the last dose (HPVc) increased from {hpvc_comp_cvg}% to {hpvc_rev_cvg}%."
txt_hpv_hpv1_const_hpvc_dec <- "Programme coverage of HPV1 among females remained constant at {hpv1_rev_cvg}% between {comp_yr} and {rev_yr}, while coverage of the last dose (HPVc) decreased from {hpvc_comp_cvg}% to {hpvc_rev_cvg}%."
txt_hpv_hpv1_inc_hpvc_const <- "Programme coverage of HPV1 among females increased from {hpv1_comp_cvg}% to {hpv1_rev_cvg}% between {comp_yr} and {rev_yr}, while coverage of the last dose (HPVc) remained constant at {hpvc_rev_cvg}%."
txt_hpv_hpv1_inc_hpvc_inc   <- "Programme coverage of HPV1 among females increased from {hpv1_comp_cvg}% to {hpv1_rev_cvg}% between {comp_yr} and {rev_yr}, and coverage of the last dose (HPVc) also increased from {hpvc_comp_cvg}% to {hpvc_rev_cvg}%."
txt_hpv_hpv1_inc_hpvc_dec   <- "Programme coverage of HPV1 among females increased from {hpv1_comp_cvg}% to {hpv1_rev_cvg}% between {comp_yr} and {rev_yr}, while coverage of the last dose (HPVc) decreased from {hpvc_comp_cvg}% to {hpvc_rev_cvg}%."
txt_hpv_hpv1_dec_hpvc_const <- "Programme coverage of HPV1 among females decreased from {hpv1_comp_cvg}% to {hpv1_rev_cvg}% between {comp_yr} and {rev_yr}, while coverage of the last dose (HPVc) remained constant at {hpvc_rev_cvg}%."
txt_hpv_hpv1_dec_hpvc_inc   <- "Programme coverage of HPV1 among females decreased from {hpv1_comp_cvg}% to {hpv1_rev_cvg}% between {comp_yr} and {rev_yr}, while coverage of the last dose (HPVc) increased from {hpvc_comp_cvg}% to {hpvc_rev_cvg}%."
txt_hpv_hpv1_dec_hpvc_dec   <- "Programme coverage of HPV1 among females decreased from {hpv1_comp_cvg}% to {hpv1_rev_cvg}% between {comp_yr} and {rev_yr}, and coverage of the last dose (HPVc) also decreased from {hpvc_comp_cvg}% to {hpvc_rev_cvg}%."
txt_hpv_single_year_both   <- "In {rev_yr}, programme coverage among females was {hpv1_rev_cvg}% for the first dose (HPV1) and {hpvc_rev_cvg}% for the final dose (HPVc)."
txt_hpv_single_year_hpv1   <- "In {rev_yr}, programme coverage of the first dose (HPV1) among females was {hpv1_rev_cvg}%."
 
# # ── DROPOUT DESCRIPTORS (reused across sections) ──────────────────────────────
txt_general_dropout_diff_higher_1 <- "{diff} percentage point higher than in {comp_yr} ({.[[comparison_col]]}%)"
txt_general_dropout_diff_higher_pp <- "{diff} percentage points higher than in {comp_yr} ({.[[comparison_col]]}%)"
txt_general_dropout_diff_lower_1 <- "{abs(diff)} percentage point lower than in {comp_yr} ({.[[comparison_col]]}%)"
txt_general_dropout_diff_lower_pp <- "{abs(diff)} percentage points lower than in {comp_yr} ({.[[comparison_col]]}%)"
txt_general_dropout_diff_same <- "the same as in {comp_yr}"

txt_cvg_increased_short <- "increased from {minusone_lbl}% in {rev_yr-1} to {recent_lbl}% in {rev_yr}"
txt_cvg_decreased_short <- "declined from {minusone_lbl}% in {rev_yr-1} to {recent_lbl}% in {rev_yr}"
txt_cvg_same_short      <- "was the same in {rev_yr} as it was in {rev_yr-1} ({minusone_lbl}%)"

# ── OVERVIEW ──────────────────────────────────────────────────────────────────
txt_ovw_vax_gt90              <- "A total of {n_vax_total} childhood vaccines are tracked for {the_ctry_name}; of these, {n_vax_gt90} reached the 90% coverage target or higher in {rev_yr}."
txt_ovw_vax_none_gt90         <- "None of the {n_vax_total} childhood vaccines tracked for {the_ctry_name} achieved coverage of 90% or higher in {rev_yr}."
txt_ovw_dtp1_cvg         <- "Coverage of the first dose of diphtheria-tetanus-pertussis-containing vaccine (DTP1) {cvg_chng_dtp1}, coverage of the third dose of DTP-containing vaccine (DTP3) {cvg_chng_dtp3}, and coverage of the first dose of the measles-containing vaccine (MCV1) {cvg_chng_mcv1} in {rev_yr}."

txt_ovw_zd_ia2030             <- "In {rev_yr}, the number of zero-dose children for DTP in {the_ctry_name} ({zd_rev_yr_lbl}) was approximately {abs_zd_pcnt_diff}% {zd_diff_txt} the annual number proposed to achieve the IA2030 target of halving zero-dose children for DTP by 2030 ({ia2030_rev_yr_lbl}), based on a linear trajectory of decline."
txt_ovw_zd_ia2030_higher      <- "In {rev_yr}, the number of zero-dose children for DTP in {the_ctry_name} ({zd_rev_yr_lbl}) was approximately {abs_zd_pcnt_diff}% higher than the annual number proposed to achieve the IA2030 target of halving zero-dose children for DTP by 2030 ({ia2030_rev_yr_lbl}), based on a linear trajectory of decline."
txt_ovw_zd_ia2030_lower       <- "In {rev_yr}, the number of zero-dose children for DTP in {the_ctry_name} ({zd_rev_yr_lbl}) was approximately {abs_zd_pcnt_diff}% lower than the annual number proposed to achieve the IA2030 target of halving zero-dose children for DTP by 2030 ({ia2030_rev_yr_lbl}), based on a linear trajectory of decline."
txt_ovw_zd_ia2030_same        <- "In {rev_yr}, the number of zero-dose children for DTP in {the_ctry_name} ({zd_rev_yr_lbl}) was approximately the same as the annual number proposed to achieve the IA2030 target of halving zero-dose children for DTP by 2030 ({ia2030_rev_yr_lbl}), based on a linear trajectory of decline."
txt_ovw_vax_gt90_summary      <- "While noting variations across countries and vaccines, {n_achieved_txt} of the {n_vax} childhood vaccines achieved an average coverage of 90% or higher within the {region_translated} region in {rev_yr}."
txt_ovw_coverage_change_summary <- "Coverage of the first dose of diphtheria-tetanus-pertussis-containing vaccine (DTP1) {dtp1_diff}, and the third dose of DTP-containing vaccine (DTP3) {dtp3_diff}. Coverage of the first dose of the vaccine against measles (MCV1) {mcv1_diff}."
txt_ovw_zero_dose_summary     <- "In {rev_yr}, the number of zero-dose children ({estimate_lbl}) was approximately {pcnt_diff}% {diff_txt} the annual goal to achieve the Immunization Agenda 2030 target of reducing the number of zero-dose children by half by 2030 in {region_translated} region ({ia2030_lbl})."
txt_ovw_ctry_level_achieved   <- "A total of {n_achieved} out of {total_ctry} countries reached target coverage (90%) for all {n_vax} antigens, representing {pct_achieved}% of the region."
txt_ovw_ctry_level_failed_one      <- "There was one country that did not meet the target coverage across all antigens: {failed_list}."
txt_ovw_ctry_level_failed_multiple <- "There were {nctry_lt90} countries that did not meet the target coverage across all antigens: {failed_list}."
txt_ovw_ctry_level_failed_none     <- "All countries successfully met the target coverage across all antigens."
txt_contents                  <- "Contents"
txt_was_1_country             <- "was {nctry_lt90} country"
txt_were_n_countries          <- "were {nctry_lt90} countries"
txt_were_no_countries         <- "were no countries"
txt_were_n_countries_short    <- "There were {n_gt90}"
txt_map_country               <- "Country"
txt_map_region                <- "Region"
txt_map_other_countries       <- "Other countries"
txt_region_includes_list      <- "The {region_translated} region includes the following {n_ctry} countries: {ctry_list_txt}."
txt_region_banner_title       <- "WUENIC Talking Points: {region_translated} Region ({regn})"
txt_region_title              <- "Countries in {region_translated} Region"
txt_ia2030_zd_proj_bar_line_y <- "# zero-dose children"
txt_ia2030_zd_proj_bar_line_title <- "Estimated number of zero-dose children,\n2000–{rev_yr} and target by 2030, {the_ctry_name}"
txt_ia2030_zd_proj_bar_line_cpt <- "Note: The Immunization Agenda 2030 (IA2030) calls on all countries to reduce the number of zero-dose children in 2019 in half by 2030.\nDark blue bars are the estimated number of zero-dose children in 2000–{rev_yr}, light blue bar is the target number of zero-dose children by 2030.\nThe line and points show the yearly progress and trajectory to meet the target by 2030, based on a linear decline."

# ──────────────────────────────────────────────────────────────────────────────
# generic coverage comparison strings to use as the first bullet for all vaccines
# If it increased compared to comp_yr...
txt_vax_inc_inc  <- "Coverage of {vax} stood at {ctry_cvg_rev}% in {rev_yr}. This is higher than in {comp_yr} ({ctry_cvg_comp}%) and higher than in {minusone_col} ({ctry_cvg_minusone}%)."
txt_vax_inc_dec  <- "Coverage of {vax} stood at {ctry_cvg_rev}% in {rev_yr}. This is higher than in {comp_yr} ({ctry_cvg_comp}%) and lower than in {minusone_col} ({ctry_cvg_minusone}%)."
txt_vax_inc_same <- "Coverage of {vax} stood at {ctry_cvg_rev}% in {rev_yr}. This is higher than in {comp_yr} ({ctry_cvg_comp}%) and the same as in {minusone_col} ({ctry_cvg_minusone}%)."

# If it decreased compared to comp_yr...
txt_vax_dec_inc  <- "Coverage of {vax} stood at {ctry_cvg_rev}% in {rev_yr}. This is lower than in {comp_yr} ({ctry_cvg_comp}%) and higher than in {minusone_col} ({ctry_cvg_minusone}%)."
txt_vax_dec_dec  <- "Coverage of {vax} stood at {ctry_cvg_rev}% in {rev_yr}. This is lower than in {comp_yr} ({ctry_cvg_comp}%) and lower than in {minusone_col} ({ctry_cvg_minusone}%)."
txt_vax_dec_same <- "Coverage of {vax} stood at {ctry_cvg_rev}% in {rev_yr}. This is lower than in {comp_yr} ({ctry_cvg_comp}%) and the same as in {minusone_col} ({ctry_cvg_minusone}%)."

# If it stayed the same compared to comp_yr...
txt_vax_sam_inc  <- "Coverage of {vax} stood at {ctry_cvg_rev}% in {rev_yr}. This is the same as in {comp_yr} ({ctry_cvg_comp}%) and higher than in {minusone_col} ({ctry_cvg_minusone}%)."
txt_vax_sam_dec  <- "Coverage of {vax} stood at {ctry_cvg_rev}% in {rev_yr}. This is the same as in {comp_yr} ({ctry_cvg_comp}%) and lower than in {minusone_col} ({ctry_cvg_minusone}%)."
txt_vax_sam_same <- "Coverage of {vax} stood at {ctry_cvg_rev}% in {rev_yr}. This is the same as in {comp_yr} ({ctry_cvg_comp}%) and the same as in {minusone_col} ({ctry_cvg_minusone}%)."

# ── DTP1 ──────────────────────────────────────────────────────────────────────
txt_dtp1_cvg_change           <- "In {rev_yr}, DTP1 coverage in {the_ctry_name} was {ctry_cvg_rev}%, compared to {ctry_cvg_comp}% in {comp_yr}."
txt_dtp1_zd_ia2030            <- "In {rev_yr}, the number of zero-dose children in {the_ctry_name} ({zd_rev_yr_lbl}) was approximately {abs_zd_pcnt_diff}% {zd_diff_txt} the annual IA2030 target ({ia2030_rev_yr_lbl})."
txt_dtp1_dropout              <- "DTP1-to-DTP3 dropout in {rev_yr} was {dropout_pct}%, {dropout_diff_txt}. {dropout_txt}"
txt_dtp1_negative_dropout     <- "DTP3 coverage surpassed DTP1 coverage by {abs_dropout_pct} percentage points in {rev_yr}, which was {dropout_diff_txt}."
txt_dtp1_change_summary       <- "The number of children vaccinated with DTP1 {direction} {pchng}% from {comp_val} in {comp_yr} to {rev_val} in {rev_yr}."
txt_dtp1_zd_ia2030_summary    <- "In {rev_yr}, the number of zero-dose children ({estimate_lbl}) was approximately {pcnt_diff}% {diff_txt} the annual goal to achieve the Immunization Agenda 2030 target in {regn} region ({ia2030_lbl})."
txt_dtp1_surviving_infants_summary <- "With {diff_abs_lbl} {moreless} surviving infants in the region compared to in {comp_yr}, {to_vax}."
txt_dtp1_top2_zd_ctry_summary <- "In {rev_yr}, {ctry_list} represented approximately {pct1}% and {pct2}% of all zero-dose children in {regn} (n = {total_zd}), respectively. {ctry1} had the highest number of zero-dose children at {n1}, and {ctry2} had the second highest at {n2}."
txt_dtp1_lowest_coverage_summary <- "The lowest DTP1 coverage was observed in {ctry1} at {pct1}%, followed by {ctry2} at {pct2}%."
txt_dtp1_none_achieved        <- "None of the {nctry} countries in {regn} achieved DTP1 coverage of 90% or higher in {rev_yr}."
txt_dtp1_share_achieved       <- "{n_gt90_txt} ({pct}%) out of {nctry} countries in the region that achieved DTP1 coverage of 90% or higher in {rev_yr}{gt90_txt}."

txt_cvg_higher_than_regional_avg <- "Coverage of {vax} in {the_ctry_name} ({ctry_cvg_rev}%) was higher than the {region_translated} regional average of {reg_avg_cvg}% in {rev_yr}."
txt_cvg_lower_than_regional_avg  <- "Coverage of {vax} in {the_ctry_name} ({ctry_cvg_rev}%) was lower than the {region_translated} regional average of {reg_avg_cvg}% in {rev_yr}."
txt_cvg_same_as_regional_avg     <- "Coverage of {vax} in {the_ctry_name} ({ctry_cvg_rev}%) was the same as the {region_translated} regional average of {reg_avg_cvg}% in {rev_yr}."

# ── DTP3 ──────────────────────────────────────────────────────────────────────
txt_dtp3_vaccinated_increased <- "The number of children vaccinated with DTP3 increased from {vacc_comp_yr_lbl} in {comp_yr} to {vacc_rev_yr_lbl} in {rev_yr}."
txt_dtp3_vaccinated_decreased <- "The number of children vaccinated with DTP3 decreased from {vacc_comp_yr_lbl} in {comp_yr} to {vacc_rev_yr_lbl} in {rev_yr}."
txt_dtp3_vaccinated_unchanged <- "The number of children vaccinated with DTP3 remained unchanged from {vacc_comp_yr_lbl} in {comp_yr} to {vacc_rev_yr_lbl} in {rev_yr}."
txt_dtp3_unvac                <- "In {rev_yr}, there were {unvac_dtp3_lbl} children un- or under-vaccinated in {the_ctry_name}."
txt_dtp3_change_summary       <- "The number of children vaccinated with DTP3 {direction} {pchng}% from {comp_val} in {comp_yr} to {rev_val} in {rev_yr}. {pop_chng_txt}"
txt_dtp3_coverage_range       <- "In {rev_yr}, DTP3 coverage ranged from {min_pct}% in {min_ctry} to {max_pct}% in {max_ctry}."
txt_dtp3_top2_unvac_summary   <- "{ctry1} had DTP3 coverage of {pct1}% and the highest absolute number of un- and undervaccinated children in the region ({unvac1}), followed by {ctry2} with {pct2}% coverage and {unvac2} un- and undervaccinated children."

# --- DTP1-DTP3 and DTP1-MCV1 DROPOUT STRINGS
txt_dropout_lower_lower   <- "In {rev_yr}, {dropout_pct}% of children who received {vax1} did not receive {vax2}. This {dropout_pct}% dropout rate was {diff_comp} percentage points lower than in {comp_yr} ({comp_pct}%) and {diff_minusone} percentage points lower than the {minusone_col} dropout rate ({minusone_pct}%)."
txt_dropout_lower_higher  <- "In {rev_yr}, {dropout_pct}% of children who received {vax1} did not receive {vax2}. This {dropout_pct}% dropout rate was {diff_comp} percentage points lower than in {comp_yr} ({comp_pct}%) but {diff_minusone} percentage points higher than the {minusone_col} dropout rate ({minusone_pct}%)."
txt_dropout_lower_same    <- "In {rev_yr}, {dropout_pct}% of children who received {vax1} did not receive {vax2}. This {dropout_pct}% dropout rate was {diff_comp} percentage points lower than in {comp_yr} ({comp_pct}%) and the same as the {minusone_col} dropout rate ({minusone_pct}%)."
txt_dropout_higher_lower  <- "In {rev_yr}, {dropout_pct}% of children who received {vax1} did not receive {vax2}. This {dropout_pct}% dropout rate was {diff_comp} percentage points higher than in {comp_yr} ({comp_pct}%) but {diff_minusone} percentage points lower than the {minusone_col} dropout rate ({minusone_pct}%)."
txt_dropout_higher_higher <- "In {rev_yr}, {dropout_pct}% of children who received {vax1} did not receive {vax2}. This {dropout_pct}% dropout rate was {diff_comp} percentage points higher than in {comp_yr} ({comp_pct}%) and {diff_minusone} percentage points higher than the {minusone_col} dropout rate ({minusone_pct}%)."
txt_dropout_higher_same   <- "In {rev_yr}, {dropout_pct}% of children who received {vax1} did not receive {vax2}. This {dropout_pct}% dropout rate was {diff_comp} percentage points higher than in {comp_yr} ({comp_pct}%) and the same as the {minusone_col} dropout rate ({minusone_pct}%)."
txt_dropout_same_lower    <- "In {rev_yr}, {dropout_pct}% of children who received {vax1} did not receive {vax2}. This {dropout_pct}% dropout rate was the same as in {comp_yr} ({comp_pct}%) but {diff_minusone} percentage points lower than the {minusone_col} dropout rate ({minusone_pct}%)."
txt_dropout_same_higher   <- "In {rev_yr}, {dropout_pct}% of children who received {vax1} did not receive {vax2}. This {dropout_pct}% dropout rate was the same as in {comp_yr} ({comp_pct}%) but {diff_minusone} percentage points higher than the {minusone_col} dropout rate ({minusone_pct}%)."
txt_dropout_same_same     <- "In {rev_yr}, {dropout_pct}% of children who received {vax1} did not receive {vax2}. This {dropout_pct}% dropout rate was the same as in {comp_yr} ({comp_pct}%) and the same as the {minusone_col} dropout rate ({minusone_pct}%)."

# ── MCV ──────────────────────────────────────────────────────────────────────
txt_mcv1_cvg_change           <- "MCV1 coverage {cvg_chng_txt}."
txt_mcv2_cvg_change_decreased           <- "Coverage of the second dose of the measles-containing vaccine (MCV2) {cvg_chng_txt}. This leaves {mcv1_unvac_lbl} children without any protection against measles and another {mcv_diff_lbl} with only partial protection."
txt_mcv2_cvg_change_increased           <- "Coverage of the second dose of the measles-containing vaccine (MCV2) {cvg_chng_txt}. This still leaves {mcv1_unvac_lbl} children without any protection against measles and another {mcv_diff_lbl} with only partial protection."

txt_mcv_dropout               <- "In {rev_yr}, {dropout_pct}% of children who received DTP1 did not receive MCV1. DTP-MCV dropout was {dropout_diff_txt}. {dropout_txt}"
txt_mcv_negative_dropout      <- "In {rev_yr}, MCV1 coverage surpassed DTP1 coverage by {abs_dropout_pct} percentage points. This {dropout_pct}% DTP-MCV dropout rate was {dropout_diff_txt}."
txt_mcv_persistent_low        <- "{persistent_low_txt}."
txt_mcv_persistent_low_yes    <- "{capital_the_name} has had MCV1 coverage below {thrshold}% for all of the last {nyrs} years."
txt_mcv_persistent_low_no     <- "{capital_the_name} has achieved MCV1 coverage above {thrshold}% over all of the last {nyrs} years."
txt_mcv_reg_rank              <- "Among {region_translated} region peers, {the_ctry_name} ranked {rank} out of {n_peers} countries in MCV1 coverage in {rev_yr}."
txt_mcv_persistent_low_single <- "One country ({list}) had MCV1 coverage below {thrshold}% for all of the last {nyrs} years."
txt_mcv_persistent_low_multi  <- "{count} countries ({list}) had MCV1 coverage below {thrshold}% for all of the last {nyrs} years."
txt_mcv_persistent_low_none   <- "Over the last {nyrs} years, no countries have had MCV1 coverage below {thrshold}%."
txt_mcv1_cvg_higher           <- "MCV1 coverage in {rev_yr} was {rev_pct}%, higher than in {comp_yr} ({comp_pct}%)."
txt_mcv1_cvg_lower            <- "MCV1 coverage in {rev_yr} was {rev_pct}%, lower than in {comp_yr} ({comp_pct}%)."
txt_mcv1_cvg_stable           <- "MCV1 coverage in {rev_yr} was {rev_pct}%, similar to {comp_yr} ({comp_pct}%)."
txt_mcv2_cvg_summary          <- "MCV2 coverage increased from {cvg_comp}% in {comp_yr} to {cvg_rev}% in {rev_yr}. This still leaves {mcv1_lbl} children without any protection and another {diff_lbl} with only partial protection against the measles virus."
txt_mcv_top_unvac_ctry        <- "{country} had the highest number of children who did not receive the measles vaccine ({unvac_n}), representing approximately {unvac_pct}% of all children unprotected against measles in {region} ({mcv1_lbl})."
txt_mcv2_no_data <- "MCV2 coverage data is not available for {the_ctry_name} in WUENIC data."

# ── DTP1-MCV1 DROPOUT ────────────────────────────────────────────────────────
txt_mcv_dropout_low    <- "In {rev_yr}, {dropout_pct}% of children who received DTP1 did not receive MCV1, which was {dropout_diff_txt}; low dropout rates imply good retention and ability to provide a full course of vaccines in infancy."
txt_mcv_dropout_medium <- "In {rev_yr}, {dropout_pct}% of children who received DTP1 did not receive MCV1, which was {dropout_diff_txt}; medium dropout rates imply moderate retention in immunization programmes."
txt_mcv_dropout_high   <- "In {rev_yr}, {dropout_pct}% of children who received DTP1 did not receive MCV1, which was {dropout_diff_txt}; high dropout rates imply poor retention in immunization programmes."
txt_mcv_diff_higher_1  <- "1 percentage point higher than in {comp_yr} ({comp_pct}%)"
txt_mcv_diff_higher_pp <- "{diff} percentage points higher than in {comp_yr} ({comp_pct}%)"
txt_mcv_diff_lower_1   <- "1 percentage point lower than in {comp_yr} ({comp_pct}%)"
txt_mcv_diff_lower_pp  <- "{diff} percentage points lower than in {comp_yr} ({comp_pct}%)"
txt_mcv_diff_same      <- "the same as in {comp_yr} ({comp_pct}%)"

# ── GENERIC DROPOUT DESCRIPTORS ──────────────────────────────────────────────
txt_dropout_low          <- "Low {vax_pair} dropout rates imply good ability to provide a complete vaccine series early in life."
txt_dropout_medium       <- "Medium {vax_pair} dropout rates imply moderate ability to provide a complete vaccine series early in life."
txt_dropout_high         <- "High {vax_pair} dropout rates imply poor ability to provide a complete vaccine series early in life."
txt_dropout_low_mcv      <- "Low DTP-MCV dropout rates imply good retention and ability to provide a full course of vaccines in infancy."
txt_dropout_medium_mcv   <- "Medium DTP-MCV dropout rates imply moderate retention in immunization programmes."
txt_dropout_high_mcv     <- "High DTP-MCV dropout rates imply poor retention in immunization programmes."
txt_dropout_diff_higher_1  <- "DTP-MCV dropout was 1 percentage point higher than in {comp_yr} ({comp_pct}%)."
txt_dropout_diff_higher_pp <- "DTP-MCV dropout was {diff} percentage points higher than in {comp_yr} ({comp_pct}%)."
txt_dropout_diff_lower_1   <- "DTP-MCV dropout was 1 percentage point lower than in {comp_yr} ({comp_pct}%)."
txt_dropout_diff_lower_pp  <- "DTP-MCV dropout was {diff} percentage points lower than in {comp_yr} ({comp_pct}%)."
txt_dropout_diff_same      <- "DTP-MCV dropout was the same as in {comp_yr} ({comp_pct}%)."

# ── HPV ──────────────────────────────────────────────────────────────────────
txt_hpv_not_introduced        <- "{ctry_name} had not introduced human pappilomavirus vaccination (HPV) as of {rev_yr}."
txt_hpv_intro_no_data         <- "{ctry_name} had introduced human pappilomavirus vaccination (HPV) as of {rev_yr} but has no {rev_yr} WUENIC HPV data."
txt_hpv_cvg_hpv1_only         <- "Programme coverage of the first dose of human papillomavirus vaccine (HPV1) among females {hpv1_diff_txt}."
txt_hpv_cvg_both              <- "Programme coverage of the first dose of human papillomavirus vaccine (HPV1) among females {hpv1_diff_txt}, and coverage of the last dose {hpvc_label} {hpvc_diff_txt}."
txt_hpv_gt90                  <- "{gt90_txt}."
txt_hpv_no_hpvc_one_yr        <- "HPVc (last dose) data is available for {ctry_name} in WUENIC but only for one year, so a year-on-year comparison is not possible and HPVc is not included in this report."
txt_hpv_no_hpvc_data          <- "HPVc (last dose) coverage data is not available for {ctry_name} in WUENIC data."
txt_hpv_unvac                 <- "In {hpv_rev_yr}, approximately {hpv1_unvac_lbl} females in {the_ctry_name} did not receive any HPV vaccination (unvaccinated)."
txt_hpv_no_unvac_data         <- "The number of unvaccinated females for HPV in {the_ctry_name} in {hpv_rev_yr} is not available in WUENIC data."
txt_hpv_reg_rank              <- "Among {region_translated} region peers, {the_ctry_name} ranked {rank} out of {n_peers_hpv} countries in {primary_hpv_label} coverage in {hpv_rev_yr}."
txt_hpv_intro_partial         <- "In {regn}, {n_ctry_intro} out of {n_ctry_total} countries ({pct_ctry_intro}%) had introduced HPV vaccination by {rev_yr}."
txt_hpv_intro_all             <- "All {n_ctry_total} countries in {regn} had introduced HPV vaccination by {rev_yr}."
txt_hpv_est_partial           <- "WUENIC HPV coverage estimates are available for {n_ctry_wuenic_hpv} of these countries in {hpv_rev_yr}."
txt_hpv_est_all_intro         <- "WUENIC HPV coverage estimates are available for all {n_ctry_wuenic_hpv} of these countries in {hpv_rev_yr}."
txt_hpv_est_all               <- "WUENIC HPV coverage estimates are available for {n_ctry_wuenic_hpv} ({pct_ctry_wuenic_hpv}%) of these countries in {hpv_rev_yr}."
txt_hpv_not_introduced_single <- "The country that had not introduced HPV vaccination is {list}."
txt_hpv_not_introduced_multi  <- "The {count} countries that had not introduced HPV vaccination are {list}."
txt_hpv_intro_no_data_single  <- "The country that has introduced HPV vaccination but does not yet have WUENIC coverage data available for {hpv_rev_yr} is {list}."
txt_hpv_intro_no_data_multi   <- "The {count} countries that have introduced HPV vaccination but do not yet have WUENIC coverage data available for {hpv_rev_yr} are {list}."
txt_hpv_unvac_girls           <- "In {hpv_rev_yr}, there were {hpv1_lbl} girls who did not receive any HPV vaccination."
txt_hpv_hpv1_increased        <- "Programme coverage of the first dose of HPV vaccine (HPV1) among girls increased from {hpv1_comp_pct}% in {hpv_comp_yr} to {hpv1_rev_pct}% in {hpv_rev_yr}."
txt_hpv_hpv1_decreased        <- "Programme coverage of the first dose of HPV vaccine (HPV1) among girls decreased from {hpv1_comp_pct}% in {hpv_comp_yr} to {hpv1_rev_pct}% in {hpv_rev_yr}."
txt_hpv_hpv1_constant         <- "Programme coverage of the first dose of HPV vaccine (HPV1) among girls remained constant at {hpv1_rev_pct}% in {hpv_rev_yr}."
txt_hpv_hpvc_increased        <- "Coverage of the last dose (HPVc) increased from {hpvc_comp_pct}% in {hpv_comp_yr} to {hpvc_rev_pct}% in {hpv_rev_yr}."
txt_hpv_hpvc_decreased        <- "Coverage of the last dose (HPVc) decreased from {hpvc_comp_pct}% in {hpv_comp_yr} to {hpvc_rev_pct}% in {hpv_rev_yr}."
txt_hpv_hpvc_constant         <- "Coverage of the last dose (HPVc) remained constant at {hpvc_rev_pct}% in {hpv_rev_yr}."

txt_hpv_changed               <- "{chng} from {minusone_val}% in {hpv_rev_yr-1} to {rev_val}% in {hpv_rev_yr}"
txt_hpv_constant              <- "{chng} at {rev_val}% between {hpv_rev_yr-1} and {hpv_rev_yr}"

txt_hpv_hpv1_vs_minusone_inc   <- "Compared with {minusone_col}, HPV1 coverage among females increased from {hpv1_minusone_cvg}% to {hpv1_rev_cvg}% in {rev_yr}."
txt_hpv_hpv1_vs_minusone_dec   <- "Compared with {minusone_col}, HPV1 coverage among females decreased from {hpv1_minusone_cvg}% to {hpv1_rev_cvg}% in {rev_yr}."
txt_hpv_hpv1_vs_minusone_const <- "Compared with {minusone_col}, HPV1 coverage among females remained constant at {hpv1_rev_cvg}% in {rev_yr}."
txt_hpv_hpvc_vs_minusone_inc   <- "Compared with {minusone_col}, HPVc coverage among females increased from {hpvc_minusone_cvg}% to {hpvc_rev_cvg}% in {rev_yr}."
txt_hpv_hpvc_vs_minusone_dec   <- "Compared with {minusone_col}, HPVc coverage among females decreased from {hpvc_minusone_cvg}% to {hpvc_rev_cvg}% in {rev_yr}."
txt_hpv_hpvc_vs_minusone_const <- "Compared with {minusone_col}, HPVc coverage among females remained constant at {hpvc_rev_cvg}% in {rev_yr}."
txt_hpv_minusone_no_data       <- "{primary_hpv_label} coverage data for {minusone_col} is not available in WUENIC data for {the_ctry_name}."
txt_hpv_no_data_for_year <- "{vaccine_label} coverage data for {yr} is not available in WUENIC data for {the_ctry_name}."

# ── REGIONAL COMPARISON ───────────────────────────────────────────────────────
txt_reg_comp_intro_has_hpvc   <- "The chart below shows how {the_ctry_name} compares to other countries in the {region_translated} region on DTP1, DTP3, MCV1, and HPVC coverage in {rev_yr}. The dashed line represents the regional average for each vaccine."
txt_reg_comp_intro_no_hpvc    <- "The chart below shows how {the_ctry_name} compares to other countries in the {region_translated} region on DTP1, DTP3, MCV1 coverage in {rev_yr}. The dashed line represents the regional average for each vaccine."
txt_reg_comp_intro            <- "The chart below shows how {the_ctry_name} compares to other countries in the {ctry_regn} region on DTP1, DTP3, MCV1{hpvc_suffix} coverage in {rev_yr}. The dashed line represents the regional average for each vaccine."
txt_reg_comp_no_hpvc_yr       <- "HPVc (last dose) data is available for {ctry_name} in WUENIC but not for {rev_yr}, so HPVc coverage is not included in the regional comparison."
txt_reg_comp_no_hpvc          <- "HPVc (last dose) data is not available for {ctry_name} in WUENIC, so HPVc coverage is not included in the regional comparison."
txt_reg_comp_hpvc_suffix      <- " and HPVc"

# ── ADDITIONAL VACCINES ───────────────────────────────────────────────────────
txt_add_vax_increased         <- "increased from {comp_val}% in {comp_yr} to {rev_val}% in {rev_yr}"
txt_add_vax_decreased         <- "decreased from {comp_val}% in {comp_yr} to {rev_val}% in {rev_yr}"
txt_add_vax_same              <- "remained the same ({comp_val}%) between {comp_yr} and {rev_yr}"
txt_add_vax_inc_inc  <- "Coverage of {vaccine_label} stood at {rev_cvg}% in {rev_yr}. This is higher than in {comp_yr} ({comp_cvg}%) and higher than in {minusone_col} ({minusone_cvg}%)."
txt_add_vax_inc_dec  <- "Coverage of {vaccine_label} stood at {rev_cvg}% in {rev_yr}. This is higher than in {comp_yr} ({comp_cvg}%) but lower than in {minusone_col} ({minusone_cvg}%)."
txt_add_vax_inc_same <- "Coverage of {vaccine_label} stood at {rev_cvg}% in {rev_yr}. This is higher than in {comp_yr} ({comp_cvg}%) and the same as in {minusone_col} ({minusone_cvg}%)."
txt_add_vax_dec_inc  <- "Coverage of {vaccine_label} stood at {rev_cvg}% in {rev_yr}. This is lower than in {comp_yr} ({comp_cvg}%) but higher than in {minusone_col} ({minusone_cvg}%)."
txt_add_vax_dec_dec  <- "Coverage of {vaccine_label} stood at {rev_cvg}% in {rev_yr}. This is lower than in {comp_yr} ({comp_cvg}%) and lower than in {minusone_col} ({minusone_cvg}%)."
txt_add_vax_dec_same <- "Coverage of {vaccine_label} stood at {rev_cvg}% in {rev_yr}. This is lower than in {comp_yr} ({comp_cvg}%) and the same as in {minusone_col} ({minusone_cvg}%)."
txt_add_vax_sam_inc  <- "Coverage of {vaccine_label} stood at {rev_cvg}% in {rev_yr}. This is the same as in {comp_yr} ({comp_cvg}%) but higher than in {minusone_col} ({minusone_cvg}%)."
txt_add_vax_sam_dec  <- "Coverage of {vaccine_label} stood at {rev_cvg}% in {rev_yr}. This is the same as in {comp_yr} ({comp_cvg}%) but lower than in {minusone_col} ({minusone_cvg}%)."
txt_add_vax_sam_same <- "Coverage of {vaccine_label} stood at {rev_cvg}% in {rev_yr}. This is the same as in {comp_yr} ({comp_cvg}%) and the same as in {minusone_col} ({minusone_cvg}%)."
txt_add_vax_single_year <- "Coverage of {vaccine_label} stood at {rev_cvg}% in {rev_yr}."
txt_add_vax_no_data <- "Coverage data for {vaccine_label} is not available for {rev_yr}."
txt_add_vax_vscomp_inc <- "Coverage of {vaccine_label} stood at {rev_cvg}% in {rev_yr}. This is higher than in {comp_yr} ({comp_cvg}%)."
txt_add_vax_vscomp_dec <- "Coverage of {vaccine_label} stood at {rev_cvg}% in {rev_yr}. This is lower than in {comp_yr} ({comp_cvg}%)."
txt_add_vax_vscomp_sam <- "Coverage of {vaccine_label} stood at {rev_cvg}% in {rev_yr}. This is the same as in {comp_yr} ({comp_cvg}%)."
txt_add_vax_vsminusone_inc <- "Coverage of {vaccine_label} stood at {rev_cvg}% in {rev_yr}. This is higher than in {minusone_col} ({minusone_cvg}%)."
txt_add_vax_vsminusone_dec <- "Coverage of {vaccine_label} stood at {rev_cvg}% in {rev_yr}. This is lower than in {minusone_col} ({minusone_cvg}%)."
txt_add_vax_vsminusone_sam <- "Coverage of {vaccine_label} stood at {rev_cvg}% in {rev_yr}. This is the same as in {minusone_col} ({minusone_cvg}%)."

# ── COVERAGE CHANGE DESCRIPTORS ───────────────────────────────────────────────
txt_cvg_stable                <- "remained relatively stable, within 1 percentage point of the {comp_yr} level"
txt_cvg_lower_than_baseline   <- "was lower than in {comp_yr}"
txt_cvg_higher_than_baseline  <- "was higher than in {comp_yr}"
txt_cvg_decreased             <- "decreased from {cvg_comp}% in {comp_yr} to {cvg_rev}% in {rev_yr}"
txt_cvg_increased             <- "increased from {cvg_comp}% in {comp_yr} to {cvg_rev}% in {rev_yr}"

txt_unvac_stable    <- "remained relatively stable between {comp_yr} and {rev_yr} at {recent_lbl}"
txt_unvac_declined  <- "declined {abs_pchng}% from {comparison_lbl} in {comp_yr} to {recent_lbl} in {rev_yr}"
txt_unvac_increased <- "increased {abs_pchng}% from {comparison_lbl} in {comp_yr} to {recent_lbl} in {rev_yr}"

# ── ZERO-DOSE DTP vs IA2030 TARGET ────────────────────────────────────────────
txt_dtp1_zd_ia2030_higher     <- "The percentage of zero-dose children was {abs_zd_pcnt_diff} percentage points higher than the IA2030 target in {rev_yr}."
txt_dtp1_zd_ia2030_lower      <- "The percentage of zero-dose children was {abs_zd_pcnt_diff} percentage points lower than the IA2030 target in {rev_yr}."
txt_dtp1_zd_ia2030_same       <- "The percentage of zero-dose children was the same as the IA2030 target in {rev_yr}."

# ── ZERO-DOSE COUNT COMPARISON (2025 vs 2019 and 2024) ────────────────────────
txt_dtp1_zd_count_inc_inc  <- "There were approximately {zd_rev_lbl} zero-dose children in {rev_yr}, more than the {zd_comp_lbl} in {comp_yr} and more than the {zd_minusone_lbl} in {minusone_col}."
txt_dtp1_zd_count_inc_dec  <- "There were approximately {zd_rev_lbl} zero-dose children in {rev_yr}, more than the {zd_comp_lbl} in {comp_yr} but fewer than the {zd_minusone_lbl} in {minusone_col}."
txt_dtp1_zd_count_inc_same <- "There were approximately {zd_rev_lbl} zero-dose children in {rev_yr}, more than the {zd_comp_lbl} in {comp_yr} and about the same as the {zd_minusone_lbl} in {minusone_col}."
txt_dtp1_zd_count_dec_inc  <- "There were approximately {zd_rev_lbl} zero-dose children in {rev_yr}, fewer than the {zd_comp_lbl} in {comp_yr} but more than the {zd_minusone_lbl} in {minusone_col}."
txt_dtp1_zd_count_dec_dec  <- "There were approximately {zd_rev_lbl} zero-dose children in {rev_yr}, fewer than the {zd_comp_lbl} in {comp_yr} and fewer than the {zd_minusone_lbl} in {minusone_col}."
txt_dtp1_zd_count_dec_same <- "There were approximately {zd_rev_lbl} zero-dose children in {rev_yr}, fewer than the {zd_comp_lbl} in {comp_yr} and about the same as the {zd_minusone_lbl} in {minusone_col}."
txt_dtp1_zd_count_sam_inc  <- "There were approximately {zd_rev_lbl} zero-dose children in {rev_yr}, about the same as the {zd_comp_lbl} in {comp_yr} but more than the {zd_minusone_lbl} in {minusone_col}."
txt_dtp1_zd_count_sam_dec  <- "There were approximately {zd_rev_lbl} zero-dose children in {rev_yr}, about the same as the {zd_comp_lbl} in {comp_yr} but fewer than the {zd_minusone_lbl} in {minusone_col}."
txt_dtp1_zd_count_sam_same <- "There were approximately {zd_rev_lbl} zero-dose children in {rev_yr}, about the same as both the {zd_comp_lbl} in {comp_yr} and the {zd_minusone_lbl} in {minusone_col}."

# ── POPULATION CONTEXT ────────────────────────────────────────────────────────
txt_pop_growth_context        <- "Due to population growth of approximately {pop_grwth}% between {comp_yr} and {rev_yr}, DTP3 coverage in {rev_yr} ({ctry_cvg_rev_dtp3}%) was lower than in {comp_yr} ({ctry_cvg_comp_dtp3}%)."

# ── PLOT LABELS ───────────────────────────────────────────────────────────────
txt_plt_dtp1_title            <- "DTP1 coverage and zero-dose children\nover time, {ctry_name}, 2000–{rev_yr}"
txt_plt_dtp3_title            <- "DTP3 coverage and un- or under-vaccinated\nchildren over time, {ctry_name}, 2000–{rev_yr}"
txt_plt_mcv_title             <- "MCV coverage and MCV zero-dose children\nover time, {ctry_name}, 2000–{rev_yr}"
txt_plt_hpv_title             <- "{hpv_vax_str}{hpv_unvac_str} over time, {ctry_name}, {first_hpv_year}–{hpv_rev_yr}"
txt_plt_hpv_title_reg         <- "{hpv_vax_str}{hpv_unvac_str} over time, {region_translated}, {first_hpv_year}–{hpv_rev_yr}"
txt_plt_reg_comp_title        <- "Coverage comparison: {ctry_name}\nvs. {region} peers, {rev_yr}"
txt_plt_add_vax_title         <- "Additional vaccine coverage (%), {ctry_name}, 2000–{rev_yr}"
txt_plt_ovw_heatmap_title     <- "Vaccine coverage (%), {ctry_name}, 2000–{rev_yr}"
txt_plt_ovw_heatmap_title_reg <- "Vaccine coverage (%), {region_translated} Region, 2000–{rev_yr}"
txt_plt_ovw_line_title        <- "Vaccine coverage over time, {ctry_name}, 2000–{rev_yr}"

txt_hpv_line_title_no_hpvc_no_unvac <- "HPV1 coverage over time, {regn}, {first_hpv_year}–{hpv_rev_yr}"
txt_hpv_line_title_no_hpvc_unvac    <- "HPV1 coverage and unvaccinated females\nover time, {regn}, {first_hpv_year}–{hpv_rev_yr}"
txt_hpv_line_title_hpvc_no_unvac    <- "HPV1 and HPVc coverage\nover time, {regn}, {first_hpv_year}–{hpv_rev_yr}"
txt_hpv_line_title_hpvc_unvac       <- "HPV1 and HPVc coverage and unvaccinated females\nover time, {regn}, {first_hpv_year}–{hpv_rev_yr}"
txt_plt_ovw_heatmap_title_vax <- "{toupper(v)} coverage, by country, {region_translated} Region, 2000-{rev_yr}"
txt_plt_ovw_heatmap_caption_vax <- "Note: Countries ordered based on descending {toupper(v)} coverage in {rev_yr}."
txt_map_coverage_title        <- "{toupper(v)} coverage (%), {region_translated}, {rev_yr}"
txt_map_disclaimer            <- "Source: WHO/UNICEF estimates of national immunization coverage, {rev_yr} revision.\nNote: This map is stylized and based on an approximate scale. This map does not reflect a position\nby UNICEF or WHO on the legal status of any country or\nterritory or the delimitation of any frontiers."
txt_map_dtp1_title            <- "DTP1 coverage (%), by country, {region_translated} Region, {rev_yr}"
txt_map_dtp3_title            <- "DTP3 coverage (%), by country, {region_translated} Region, {rev_yr}"
txt_map_mcv1_title            <- "MCV1 coverage (%), by country, {region_translated} Region, {rev_yr}"
txt_dtp1_heatmap_title        <- "DTP1 coverage (%), by country, {region_translated} Region, 2000–{rev_yr}"
txt_dtp3_heatmap_title        <- "DTP3 coverage (%), by country, {region_translated} Region, 2000–{rev_yr}"
txt_mcv1_heatmap_title        <- "MCV1 coverage (%), by country, {region_translated} Region, 2000–{rev_yr}"
txt_map_title_full            <- "<span style='color:#1CABE2;'>{ctry_name}</span> in the '{region_for_country}' region"
txt_wuenic_source             <- "Source: WHO/UNICEF estimates of national immunization coverage, {rev_yr} revision."

txt_appendix_wuenic_revision  <- str_glue("These talking points present the latest WUENIC estimates (published 15 July {rev_yr+1}).")

# ── COLLECT ALL txt_ VARIABLES ────────────────────────────────────────────────
text_vars_en <- mget(ls(pattern = "^txt_"))





# txt_surv_inf_vax_1       <- "Vaccinating approximately the same number of children as currently reached will be sufficient due to the anticipated decrease or relatively small increases in the birth cohort."
# txt_surv_inf_vax_2       <- "Maintaining current coverage requires vaccinating an increasing number of children, which will require substantial increases in immunization programme and health system capacity."
# txt_surv_inf_vax_3       <- "For vaccine coverage to increase, the number of children vaccinated needs to either increase or decline at a slower rate than the decline in surviving infant target population."

# txt_plt_hpv_both_unvac <- "HPV1 and HPVc coverage and unvaccinated females"
# txt_plt_hpv_both_only <- "HPV1 and HPVc coverage"
# txt_plt_hpv1_unvac <- "HPV1 coverage and unvaccinated females"
# txt_plt_hpv1_only <- "HPV1 coverage"

# txt_hpv_gt90_below80_up       <- "HPVc coverage remains well below the IA2030 target of 90%, though it is trending upward."
# txt_hpv_gt90_below80          <- "HPVc coverage remains well below the IA2030 target of 90%."
# txt_hpv_gt90_near_up          <- "HPVc coverage is approaching the IA2030 target of 90% and is trending upward."
# txt_hpv_gt90_near             <- "HPVc coverage is approaching but has not yet reached the IA2030 target of 90%."
# txt_hpv_gt90_achieved         <- "HPVc coverage has reached the IA2030 target of 90%."
# txt_hpv_gt90_exceeded         <- "HPVc coverage has exceeded the IA2030 target of 90%."

# txt_vacc_increased            <- "increased"
# txt_vacc_decreased            <- "decreased"
# txt_vacc_same                 <- "remained the same"
# txt_vacc_constant             <- "remained constant"
# txt_moreless_fewer            <- "fewer"
# txt_moreless_more             <- "more"
# txt_moreless_same             <- "same"

# txt_plt_ia2030_caption        <- "Dotted line shows the IA2030 target of 90% coverage"
# txt_plt_reg_comp_subtitle     <- "Dashed line = regional average"
# txt_plt_dtp1_legend_cvg       <- "DTP1 coverage"
# txt_plt_dtp1_legend_zd        <- "Zero-dose children"
# txt_plt_dtp3_legend_cvg       <- "DTP3 coverage"
# txt_plt_dtp3_legend_unvac     <- "Un- or Under-Vaccinated Children"
# txt_plt_mcv1_legend_cvg       <- "MCV1 coverage"
# txt_plt_mcv2_legend_cvg       <- "MCV2 coverage"
# txt_plt_mcv_legend_zd         <- "MCV zero-dose children"
# txt_plt_hpv1_legend_cvg       <- "HPV1 coverage"
# txt_plt_hpvc_legend_cvg       <- "HPVc coverage"
# txt_plt_hpv_legend_unvac      <- "Unvaccinated females"
# txt_plt_cvg_pct               <- "Coverage (%)"
# txt_plt_cvg_pct_legend        <- "Vaccine coverage (%)  "
# txt_plt_year                  <- "Year"
# txt_plt_zd_children           <- "Zero-dose children"
# txt_plt_unvac_females         <- "Unvaccinated females (count)"
# txt_plt_unvac_undervac        <- "Un- or under-vaccinated children"
# txt_plt_reg_comp_peers        <- "Peers"

# ── SECTION HEADERS ──────────────────────────────────────────────────────────
# txt_sec_overview              <- "Overview"
# txt_sec_banner_title          <- "WUENIC Talking Points"
# txt_sec_banner_revision       <- "Revision Year:"
# txt_sec_dtp1                  <- "DTP1: Reaching zero-dose children"
# txt_sec_dtp3                  <- "DTP3: A marker of routine immunization service delivery to children"
# txt_sec_mcv                   <- "MCV: Canary in the coal mine"
# txt_sec_hpv                   <- "HPV"
# txt_sec_reg_comp              <- "Regional Comparison"
# txt_sec_add_vax               <- "Additional Vaccines"
# txt_sec_appendix              <- "Appendix"

# ── APPENDIX ─────────────────────────────────────────────────────────────────
# txt_appendix_wuenic_header    <- "WHO/UNICEF Estimates of National Immunization Coverage (WUENIC)"
# txt_appendix_wuenic_body      <- "Each year, WHO and UNICEF review national immunization data from Member States, including administrative and official coverage, survey estimates and contextual information, and use rules-based data triangulation approach to assess coverage. Estimates are produced independently, without borrowing data from other countries, and are not based on ad hoc adjustments. In some cases, they rely on a single source, typically nationally reported coverage. When data for a specific country-vaccine-year are unavailable, values from adjacent years are interpolated or extrapolated, and conflicting sources are assessed to determine the most reliable estimate, considering potential biases and expert opinion."
# txt_appendix_methods_header   <- "Methods"
# txt_appendix_definitions_header <- "Definitions of immunization terms:"
# txt_appendix_resources_header <- "Additional resources:"

# ── DEFINITIONS ───────────────────────────────────────────────────────────────
# txt_def_bcg   <- "Bacillus Calmette-Guerin (BCG): vaccine against tuberculosis"
# txt_def_hepbb <- "Hepatitis B birth dose, given within 24 hours after birth (HepBB)"
# txt_def_dtp   <- "Diphtheria, tetanus, and pertussis vaccine, first dose (DTP1) and third dose (DTP3)"
# txt_def_hepb3 <- "Hepatitis B vaccine, third dose (HepB3)"
# txt_def_hib3  <- "Haemophilus influenzae type B vaccine, third dose (Hib3)"
# txt_def_ipv   <- "Inactivated polio vaccine, first dose (IPV1) and last dose (IPVC)"
# txt_def_mcv   <- "Measles containing vaccine, first dose (MCV1) and second dose (MCV2)"
# txt_def_rotac <- "Rotavirus vaccine, last dose (RotaC)"
# txt_def_pcv3  <- "Pneumococcal vaccine, last dose (PCV)"
# txt_def_yfv   <- "Yellow Fever vaccine (YFV)"
# txt_def_menga <- "Meningococcal A vaccine (MengA)"
# txt_def_hpv   <- "Human Papillomavirus vaccine, first dose (HPV1) and last dose (HPVc)"
